### PR TITLE
added insertion sort

### PR DESCRIPTION
**Pull request by Draco9421**
insertion sort

### CODE REVIEW

**Comment by Draco9421** [comment]
@akash2408 @deo002 please review  my PR

**Comment by akash2408** [comment]
> @akash2408 @deo002 please review my PR
@Draco9421 please make the start and stop buttom equal

**Comment by Draco9421** [comment]
> > @akash2408 @deo002 please review my PR
> @Draco9421 please make the start and stop buttom equal

Fuck of you noob(allah hu akbhar) , itna hi designing karni hoti to designing team me nahi hota me.

**Comment by akash2408** [comment]
> > > @akash2408 @deo002 please review my PR
> > > @Draco9421 please make the start and stop buttom equal
> 
> Fuck of you noob(allah hu akbhar) , itna hi designing karni hoti to designing team me nahi hota me.

or motherfucker gif kiska dala hai?

**Comment by Draco9421** [comment]
> > > > @akash2408 @deo002 please review my PR
> > > > @Draco9421 please make the start and stop buttom equal
> > 
> > Fuck of you noob(allah hu akbhar) , itna hi designing karni hoti to designing team me nahi hota me.
> 
> or motherfucker gif kiska dala hai?

Insertion sort

**Comment by akash2408** [comment]
> > > > > @akash2408 @deo002 please review my PR
> > > > > @Draco9421 please make the start and stop buttom equal
> > > 
> > > 
> > > Fuck of you noob(allah hu akbhar) , itna hi designing karni hoti to designing team me nahi hota me.
> > 
> > 
> > or motherfucker gif kiska dala hai?
> 
> Insertion sort

index.ejs me bhi toh dal u blood shit

**Comment by Draco9421** [comment]
> > > > > > @akash2408 @deo002 please review my PR
> > > > > > @Draco9421 please make the start and stop buttom equal
> > > > 
> > > > 
> > > > Fuck of you noob(allah hu akbhar) , itna hi designing karni hoti to designing team me nahi hota me.
> > > 
> > > 
> > > or motherfucker gif kiska dala hai?
> > 
> > 
> > Insertion sort
> 
> index.ejs me bhi toh dal u blood shit

ohh my bad niggaaa

**Comment by Draco9421** [comment]
Merge karo

**Comment by Draco9421** [comment]
accept karo naa BC

**Comment by akash2408** [comment]
NiCE workkk

**Pull request merged**
